using JetBrains.Annotations;
using MCM.Abstractions.Base.Global;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Xml;
using TaleWorlds.CampaignSystem;
using TaleWorlds.CampaignSystem.Party;
using TaleWorlds.CampaignSystem.Roster;
using TaleWorlds.CampaignSystem.Settlements;
using TaleWorlds.CampaignSystem.Settlements.Workshops;
using TaleWorlds.Core;
using TaleWorlds.Library;
using TaleWorlds.MountAndBlade.GauntletUI.AutoGenerated0;

namespace childrenGrowFaster
{
    public class SubModuleBehaviour : CampaignBehaviorBase
    {
        private bool isKidnapped = false;
        public override void RegisterEvents()
        {
            CampaignEvents.DailyTickEvent.AddNonSerializedListener(this, OnDailyTick2);
        }

        public override void SyncData(IDataStore dataStore)
        {
        }

        private void OnDailyTick2()
        {
            if (GlobalSettings<SubModuleSettings>.Instance.spouseEventsEnabled)
            {
                if (Hero.MainHero.Spouse != null && !Hero.MainHero.Spouse.IsPregnant)
                {
                    FireRandomSpouseEvent();
                }
            }
        }

        private void FireRandomSpouseEvent()
        {
            var events = new List<Action> { SpouseEvent1, SpouseEvent2, SpouseEvent3, SpouseEvent4 };
            if (MBRandom.RandomFloat < GlobalSettings<SubModuleSettings>.Instance.eventChance)
            {
                events[MBRandom.RandomInt(events.Count)]();
            }
        }

        private void SpouseEvent1()
        {
            int daysSinceLastKidnapping = 0;
            Hero spouse = Hero.MainHero.Spouse;
            if (spouse == null || spouse.IsPrisoner || spouse.IsPregnant) return;

            var nearestBanditParty = MobileParty.All.Where(p => p.IsBandit && p.IsActive && p.IsVisible && p.IsMoving)
                .OrderBy(p => p.GetPosition().Distance(spouse.CurrentSettlement.GetPosition()))
                .FirstOrDefault();

            if (nearestBanditParty != null && spouse.CurrentSettlement != Hero.MainHero.CurrentSettlement)
            {
                Random random = new Random();
                if (random.Next(0, 11) <= GlobalSettings<SubModuleSettings>.Instance.eventChance)
                {
                    isKidnapped = true;
                    InformationManager.DisplayMessage(new InformationMessage($"{spouse.Name} has been kidnapped by bandits!", Colors.Red));
                }
                if (isKidnapped)
                {
                    daysSinceLastKidnapping++;
                    nearestBanditParty.AddPrisoner(spouse.CharacterObject, 1);
                    Campaign.Current.VisualTrackerManager.RegisterObject(nearestBanditParty);
                    InformationManager.DisplayMessage(new InformationMessage("The bandit party has been marked on your map.", Colors.Red));
                    if (!nearestBanditParty.PrisonRoster.Contains(spouse.CharacterObject)) isKidnapped = false;

                    if (daysSinceLastKidnapping > 5)
                    {
                        InformationManager.DisplayMessage(new InformationMessage($"Your spouse has been in captivity for {daysSinceLastKidnapping} days! You should rescue them soon.", Colors.Red));
                    }
                }
            }

        }

        private void SpouseEvent2()
        {
            Hero spouse = Hero.MainHero.Spouse;
            if (spouse == null) return;

            if (spouse.CurrentSettlement != null &&
                spouse.CurrentSettlement != Hero.MainHero.CurrentSettlement &&
                !isKidnapped)
            {
                int gainedAmount = MBRandom.RandomInt(500, 1000);

                Hero.MainHero.ChangeHeroGold(gainedAmount);
                InformationManager.DisplayMessage(
                    new InformationMessage($"{spouse.Name} has earned you {gainedAmount} gold!", Colors.Green));
            }
        }

        private void SpouseEvent3()
        {
            List<Workshop> workshops = new List<Workshop>();
            workshops.AddRange(Hero.MainHero.OwnedWorkshops);
            foreach (Workshop workshop in workshops)
            {
                Hero spouse = Hero.MainHero.Spouse;
                if (workshop.Settlement != Hero.MainHero.CurrentSettlement && workshop.Settlement == spouse.CurrentSettlement && workshop != null)
                {
                    int randomProfit = MBRandom.RandomInt(100, 900);
                    workshop.ChangeGold(randomProfit);
                    InformationManager.DisplayMessage(new InformationMessage($"Your spouse has boosted the profits of {workshop.Name} by {randomProfit} gold!", Colors.Green));
                }
            }
        }

        private void SpouseEvent4()
        {
            Hero spouse = Hero.MainHero.Spouse;

            foreach (Settlement s in Settlement.All)
            {
                if (!IsValidSettlement(s, spouse)) return;

                TroopRoster garrisonRoster = s.Town.GarrisonParty.MemberRoster;
                if (garrisonRoster == null) return;
                GiveXP(garrisonRoster, s, spouse);
            }
        }

        private bool IsValidSettlement(Settlement s, Hero spouse)
        {
            return s.OwnerClan == Hero.MainHero.Clan
                && spouse.CurrentSettlement == s
                && Hero.MainHero.CurrentSettlement != spouse.CurrentSettlement
                && s != null;
        }

        private void GiveXP(TroopRoster garrisonRoster, Settlement s, Hero spouse)
        {
            foreach (TroopRosterElement troop in garrisonRoster.GetTroopRoster())
            {
                if (troop.Character == null) continue;

                var randomXP = MBRandom.RandomInt(100, 999);
                var skills = typeof(DefaultSkills).GetFields();
                foreach (var skill in skills)
                {
                    if (skill.GetValue(null) is SkillObject skillObject)
                    {
                        troop.Character.HeroObject?.AddSkillXp(skillObject, randomXP);
                        InformationMessage message = new InformationMessage(
                            $"{spouse.Name}'s leadership & steward skills have increased the xp of garrisoned troops in {s.Name} by {randomXP}",
                            Colors.Green);
                        InformationManager.DisplayMessage(message);
                    }
                }
            }
        }
    }
}